version: "3"
services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./app/:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    expose:
      - "${APP_PORT}"
